server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  routes:
  #标识你服务的名字，这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
    user-center:
    #服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
    #这里zuul是自动依赖hystrix，ribbon的，不是面向单机
      path: /user-center/**
      #这里一定要是你Eureka注册中心的服务的名称，是所以这里配置serviceId因为跟eureka结合了，如果单独使用zuul,那么就必须写自己机器的IP了，
      #如url:http://localhost:8080/  这样的不好就是写死IP了，万一这IP挂了，这高可用性，服务注册那套东西就用不起来了
      serviceId: user-center

    eruake-client:
      path: /eruake-client/**
      serviceId: eruake-client

eureka:
  client:
    serviceUrl:
      defaulyZone: http://localhost:8889/eureka/,http://localhost:8890/eureka/