server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  routes:
    user-center:
      path: /user-center/**
      serviceId: user-service
    eruake-client:
      path: /eruake-client/**
      serviceId: user-service
eureka:
  client:
    serviceUrl:
      defaulyZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/