server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  routes:
    user-center:
      path: /user-center/**
      serviceId: user-center
    eruake-client:
      path: /eruake-client/**
      serviceId: eruake-client
eureka:
  client:
    serviceUrl:
      defaulyZone: http://localhost:8889/eureka/,http://localhost:8890/eureka/