server:
  port: 7000
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wxijun/springcloud-config.git
          username: wxijun
          password: wxjun027
#          search-paths: springcloud-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/